#!/bin/bash -e

# Assumes you 'cd test' before running
EPATH=..



# Usage: ./bfwi [options] input_dir dest_parent_dir
# options:
#   -h              help
#   -H              show assigned input values? (debugging)
#   -p              print file diagnostics?
#   -n <threads>    number of threads
#   -d <delim>      delimiter (one char)
#   -x              handle xattrs?
#   -P              print directories?
#   -b              build index?
#   -o <out_fname>  output file




# run bfwi and send output to screen
echo
echo "out to screen"
rm -f  testout*
rm -rf testdirdup
$EPATH/bfwi -p -n 2 -xPb testdir testdirdup




# run to output files testout.*
echo
echo "send to output files"
rm -f  testout*
rm -rf testdirdup
$EPATH/bfwi -p -n 2 -xPb -o testout testdir testdirdup

ls -l testout*
for F in testout*; do echo; echo $F; cat $F; done
ls -lR testdirdup
