#!/usr/bin/env bash

set -e

ORIGIN="$(dirname ${BASH_SOURCE[0]})"

# go to the root of the GUFI directory
cd "$(dirname ${ORIGIN})"

# generate a directory
root="$(mktemp -d ${ORIGIN}/XXXXXXXXXX)"
src="${root}/testdir"
dst="${root}/testgufi/"

# always remove root after it is created
function cleanup {
    rm -rf "${root}"
}

trap cleanup EXIT

# create the original tree
"${ORIGIN}/generatetree" -d "${src}"

# read it into GUFI
./bfwi -t "${dst}" "${src}" 2>/dev/null

dst="$(echo ${dst} | tr -s /)" # clean up slashes
dst="${dst%/}"                 # remove last slash

if [[ "${src}" =~ ^/ ]]; then
    dst="${dst}${src}"
else
    dst="${dst}/${src}"
fi

# do not exit after first error
set +e

# keep track of errors to use as return code
error=0

# get the uid and gid
GID="$(id -g)"

# compare files
echo "Compare files"
diff <(./gufi_find "${root}" -path "${dst}" -type "f" --select "path() || '/' || name as name, type, mode, nlink, uid, gid, size, linkname" | sort) <(
    (
        echo "${dst}/1KB|f|33060|1|${UID}|${GID}|1024||"
        echo "${dst}/1MB|f|33060|1|${UID}|${GID}|1048576||"
        echo "${dst}/directory/executable|f|33279|1|${UID}|${GID}|0||"
        echo "${dst}/directory/readonly|f|33060|1|${UID}|${GID}|0||"
        echo "${dst}/directory/subdirectory/repeat_name|f|33060|1|${UID}|${GID}|0||"
        echo "${dst}/directory/writable|f|33206|1|${UID}|${GID}|0||"
        echo "${dst}/empty_file|f|33060|1|${UID}|${GID}|0||"
        echo "${dst}/.hidden|f|33060|1|${UID}|${GID}|0||"
        echo "${dst}/old_file|f|33060|1|${UID}|${GID}|0||"
        echo "${dst}/repeat_name|f|33060|1|${UID}|${GID}|0||"
        echo "${dst}/unusual, name?#|f|33060|1|${UID}|${GID}|0||"
    ) | sort) && echo "No Differences"
error=$(($error + $?))

# compare files and symlinks
echo
echo "Compare files and symlinks"
diff <(./gufi_find "${root}" -path "${dst}" --select "path() || '/' || name as name, type, mode, nlink, uid, gid, linkname" | sort) <(
    (
        echo "${dst}/1KB|f|33060|1|${UID}|${GID}||"
        echo "${dst}/1MB|f|33060|1|${UID}|${GID}||"
        echo "${dst}/directory/executable|f|33279|1|${UID}|${GID}||"
        echo "${dst}/directory/readonly|f|33060|1|${UID}|${GID}||"
        echo "${dst}/directory/subdirectory/directory_symlink|l|41471|1|${UID}|${GID}|$(realpath ${src})/directory/subdirectory|"
        echo "${dst}/directory/subdirectory/repeat_name|f|33060|1|${UID}|${GID}||"
        echo "${dst}/directory/writable|f|33206|1|${UID}|${GID}||"
        echo "${dst}/empty_file|f|33060|1|${UID}|${GID}||"
        echo "${dst}/file_symlink|l|41471|1|${UID}|${GID}|$(realpath ${src})/1KB|"
        echo "${dst}/.hidden|f|33060|1|${UID}|${GID}||"
        echo "${dst}/old_file|f|33060|1|${UID}|${GID}||"
        echo "${dst}/repeat_name|f|33060|1|${UID}|${GID}||"
        echo "${dst}/unusual, name?#|f|33060|1|${UID}|${GID}||"
    ) | sort) && echo "No Differences"
error=$(($error + $?))

exit $error
