#!/usr/bin/env bash

set -e

if [[ "$#" -ne "1" ]]; then
    echo "Syntax: $0 non-existent-path"
    exit 1
fi;

root="$1"
src="${root}/testdir"
dst="${root}/testgufi/"

if [[ -d "${root}" ]]; then
    echo "Please provide the name of a non-existent directory"
    exit 1
fi;

# go to the root GUFI directory
cd "$(dirname $(dirname $0))"

# build the directory in case it doesn't exist
mkdir -p "${root}"

# always remove root after it is created
function cleanup {
    rm -rf "${root}"
}

trap cleanup EXIT

# create the original tree
test/generatetree -d "${src}"

# read it into GUFI
./bfwi -t "${dst}" "${src}" 2>/dev/null

dst="${dst}${src}"

# do not exit after first error
set +e

# compare files
echo "Compare files"
diff <(./gufi_find "${dst}" -type "f" --select "path() || '/' || name as name, type, modetotxt(mode), nlink, uid, gid, size, linkname" --root "${root}" 2>/dev/null | sort) <(
    (
        echo "${dst}/1KB|f|-rw-rw-rw-|1|1001|1001|1024||"
        echo "${dst}/1MB|f|-rw-rw-rw-|1|1001|1001|1048576||"
        echo "${dst}/directory/executable|f|-rwxrwxrwx|1|1001|1001|0||"
        echo "${dst}/directory/readonly|f|-r--r--r--|1|1001|1001|0||"
        echo "${dst}/directory/subdirectory/repeat_name|f|-rw-rw-rw-|1|1001|1001|0||"
        echo "${dst}/directory/writeonly|f|--w--w--w-|1|1001|1001|0||"
        echo "${dst}/empty_file|f|-rw-rw-rw-|1|1001|1001|0||"
        echo "${dst}/.hidden|f|-rw-rw-rw-|1|1001|1001|0||"
        echo "${dst}/old_file|f|-rw-rw-rw-|1|1001|1001|0||"
        echo "${dst}/repeat_name|f|-rw-rw-rw-|1|1001|1001|0||"
        echo "${dst}/unusual, name?#|f|-rw-rw-rw-|1|1001|1001|0||"
    ) | sort) && echo "No Differences"

# compare files and symlinks
echo
echo "Compare files and symlinks"
diff <(./gufi_find "${dst}" --select "path() || '/' || name as name, type, modetotxt(mode), nlink, uid, gid, linkname" --root "${root}" 2>/dev/null | sort) <(
    (
        echo "${dst}/1KB|f|-rw-rw-rw-|1|1001|1001||"
        echo "${dst}/1MB|f|-rw-rw-rw-|1|1001|1001||"
        echo "${dst}/directory/executable|f|-rwxrwxrwx|1|1001|1001||"
        echo "${dst}/directory/readonly|f|-r--r--r--|1|1001|1001||"
        echo "${dst}/directory/subdirectory/directory_symlink|l|-rwxrwxrwx|1|1001|1001|$(realpath ${src})/directory/subdirectory|"
        echo "${dst}/directory/subdirectory/repeat_name|f|-rw-rw-rw-|1|1001|1001||"
        echo "${dst}/directory/writeonly|f|--w--w--w-|1|1001|1001||"
        echo "${dst}/empty_file|f|-rw-rw-rw-|1|1001|1001||"
        echo "${dst}/file_symlink|l|-rwxrwxrwx|1|1001|1001|$(realpath ${src})/1KB|"
        echo "${dst}/.hidden|f|-rw-rw-rw-|1|1001|1001||"
        echo "${dst}/old_file|f|-rw-rw-rw-|1|1001|1001||"
        echo "${dst}/repeat_name|f|-rw-rw-rw-|1|1001|1001||"
        echo "${dst}/unusual, name?#|f|-rw-rw-rw-|1|1001|1001||"
    ) | sort) && echo "No Differences"

exit 0
