language: c

git:
    depth: 5

stages:
    - test
    - install
    - deploy

matrix:
    include:
        # Ubuntu Xenial
        - stage: test
          os: linux
          sudo: false
          dist: xenial
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-xenial-7
              packages:
                - attr
                - cmake
                - clang-7
                - libattr1-dev
                - libfuse-dev
                - libpcre3-dev
                - pkg-config
              update: true
          env:
            - C_COMPILER=clang-7
            - CXX_COMPILER=clang++-7
            - BUILD=cmake
            - CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=Debug
          script: contrib/travis/xenial.sh

        # OpenSUSE 12.3 + Tumbleweed Repo
        - stage: test
          os: linux
          sudo: true
          dist: xenial
          addons:
              apt:
                  update: false
          services: docker
          env:
            - C_COMPILER=clang-7
            - CXX_COMPILER=clang++-7
            - BUILD=cmake
            - CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=Debug
            - DOCKER_IMAGE=saltstack/opensuse-12.3-minimal
          script:
            - docker run --rm --privileged --cap-add=SYS_ADMIN --device /dev/fuse -v $(realpath .):/GUFI -w /GUFI -e C_COMPILER -e CXX_COMPILER -e BUILD -e CMAKE_FLAGS "${DOCKER_IMAGE}" bash -c contrib/travis/suse12.3.sh

        # CentOS 7
        - stage: test
          os: linux
          sudo: true
          dist: xenial
          addons:
              apt:
                  update: false
          services: docker
          env:
            - C_COMPILER=clang
            - CXX_COMPILER=clang++
            - BUILD=cmake
            - CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=Debug
            - DOCKER_IMAGE=centos:7
          script:
            - docker run --rm --privileged --cap-add=SYS_ADMIN --device /dev/fuse -v $(realpath .):/GUFI -w /GUFI -e C_COMPILER -e CXX_COMPILER -e BUILD -e CMAKE_FLAGS "${DOCKER_IMAGE}" bash -c contrib/travis/centos7.sh

        # CentOS 8
        - stage: test
          os: linux
          sudo: true
          dist: xenial
          addons:
              apt:
                  update: false
          services: docker
          env:
            - C_COMPILER=clang
            - CXX_COMPILER=clang++
            - BUILD=cmake
            - CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=Debug
            - DOCKER_IMAGE=centos:8
          script:
            - docker run --rm --privileged --cap-add=SYS_ADMIN --device /dev/fuse -v $(realpath .):/GUFI -w /GUFI -e C_COMPILER -e CXX_COMPILER -e BUILD -e CMAKE_FLAGS "${DOCKER_IMAGE}" bash -c contrib/travis/centos8.sh

        # macOS 10.13 CMake
        - stage: test
          os: osx
          osx_image: xcode10.1
          sudo: false
          env:
              - C_COMPILER=gcc
              - CXX_COMPILER=g++
              - BUILD=cmake
          script: contrib/travis/osx.sh

        # macOS 10.13 make
        - stage: test
          os: osx
          osx_image: xcode10.1
          sudo: false
          env:
              - C_COMPILER=gcc
              - CXX_COMPILER=g++
              - BUILD=make
          script: contrib/travis/osx.sh

        # Test make install and the generic RPM
        - stage: install
          os: linux
          sudo: true
          dist: xenial
          addons:
              apt:
                  update: false
          services: docker
          env:
            - C_COMPILER=clang
            - CXX_COMPILER=clang++
            - BUILD=cmake
            - CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=Debug
            - DOCKER_IMAGE=centos:7
          script:
            - docker run -it -d --name "${TRAVIS_JOB_NUMBER}" --privileged --cap-add=SYS_ADMIN --device /dev/fuse -v $(realpath .):/GUFI -w /GUFI -e C_COMPILER -e CXX_COMPILER -e BUILD -e CMAKE_FLAGS "${DOCKER_IMAGE}"
            - docker exec "${TRAVIS_JOB_NUMBER}" bash -c contrib/travis/centos7.sh
            # install with make
            - docker exec "${TRAVIS_JOB_NUMBER}" bash -c contrib/travis/make_install.sh
            # install generic RPM
            - docker exec "${TRAVIS_JOB_NUMBER}" bash -c contrib/travis/generic_rpm.sh

        # Test Server and Client RPMs
        - stage: install
          os: linux
          sudo: true
          dist: xenial
          addons:
              apt:
                  update: false
          services: docker
          env:
            - C_COMPILER=clang
            - CXX_COMPILER=clang++
            - BUILD=cmake
            - CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DCLIENT=On"
            - DOCKER_IMAGE=centos:7
          script:
            - docker run -it -d --name "${TRAVIS_JOB_NUMBER}" --privileged --cap-add=SYS_ADMIN --device /dev/fuse -v $(realpath .):/GUFI -w /GUFI -e C_COMPILER -e CXX_COMPILER -e BUILD -e CMAKE_FLAGS "${DOCKER_IMAGE}"
            - docker exec "${TRAVIS_JOB_NUMBER}" bash -c contrib/travis/centos7.sh
            # install the server and client RPMs
            - docker exec "${TRAVIS_JOB_NUMBER}" bash -c contrib/travis/rpms.sh

        # Upload a tarball if the job was triggered by a user or cron
        - stage: deploy
          os: linux
          sudo: false
          dist: xenial
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-xenial-7
              packages:
                - attr
                - bsd-mailx
                - cmake
                - clang-7
                - libattr1-dev
                - libfuse-dev
                - libpcre3-dev
              update: true
          script:
            - true
          deploy:
            provider: script
            skip-cleanup: true
            script: bash contrib/travis/deploy.sh
            on:
              tags: false
              all_branches: true
              condition: (("${TRAVIS_EVENT_TYPE}" = "api") || ("${TRAVIS_EVENT_TYPE}" = "cron"))

        # Build and push release packages
        - stage: deploy
          os: linux
          sudo: true
          dist: xenial
          addons:
            apt:
              update: false
          services: docker
          env:
            - C_COMPILER=clang
            - CXX_COMPILER=clang++
            - BUILD=cmake
            - CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=Release
            - DOCKER_IMAGE=centos:7
          script:
            - docker run -it -d --name "${TRAVIS_JOB_NUMBER}" --privileged --cap-add=SYS_ADMIN --device /dev/fuse -v $(realpath .):/GUFI -w /GUFI -e C_COMPILER -e CXX_COMPILER -e BUILD -e CMAKE_FLAGS "${DOCKER_IMAGE}"
            - docker exec "${TRAVIS_JOB_NUMBER}" bash -c contrib/travis/centos7.sh
            - docker exec "${TRAVIS_JOB_NUMBER}" yum install -y rpm-build
            - docker exec "${TRAVIS_JOB_NUMBER}" cmake build
            - docker exec "${TRAVIS_JOB_NUMBER}" make -C build package
          deploy:
            provider: releases
            api_key: $GH_TOKEN
            file_glob: true
            file:
              - "build/*.rpm"
            skip_cleanup: true
            on:
              tags: true
              all_branches: true
