language: c
sudo: false

branches:
    only:
        - gufi_find

os:
    - linux
    - osx

env:
    - NIGHTLY=nightly.tar.gz

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - cmake
            - libsqlite3-dev
            - libfuse-dev
            - npm

script:
    - make
    - make test
    - test/generatetree testdir
    - test/runtests testdir testdir.gufi
    - test/verifyknowntree
    - test/googletest/test

after_success:
    # https://www.npmjs.com/package/travis-deploy-once
    - npm install -g travis-deploy-once
    - tar -czf "${NIGHTLY}" $(git ls-tree --full-tree --name-only -r HEAD | grep -v ${NIGHTLY})

deploy:
    provider: script
    script: travis-deploy-once nightly.sh
    on:
        branch: master
        condition: "${TRAVIS_EVENT_TYPE}" = "cron"
        tags: false