#!/bin/bash -e

function run() {
    echo
    echo "--- $@"
    ( exec "$@" 2>&1 )
}


IN=test/in
OUT=test/out


run rm -rf $IN
run rm -rf $OUT

run ./make_testdirs -d 128 -f 128 $IN



# walk input-tree test/in, producing GUFI index tree under test/out/test/in
# this tree will have file and dir DBs, but no tree-summary
run ./bfwi -t test/out -n 2 -P -b  $IN


# generate tree-summary, as well
run ./gufi_treesummary -P -n 2 $OUT/$IN


# Run some queries in the tree ...
run ./bfq -Pp -n 1 \
    -S "SELECT path(),name, type, size, datetime(mtime,'unixepoch') FROM vsummarydir;" \
    -E "SELECT path(),name, type, size, datetime(mtime,'unixepoch') FROM entries;" \
    $OUT/$IN \
    | more
