#!/usr/bin/env bash
# This file is part of GUFI, which is part of MarFS, which is released
# under the BSD license.
#
#
# Copyright (c) 2017, Los Alamos National Security (LANS), LLC
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# From Los Alamos National Security, LLC:
# LA-CC-15-039
#
# Copyright (c) 2017, Los Alamos National Security, LLC All rights reserved.
# Copyright 2017. Los Alamos National Security, LLC. This software was produced
# under U.S. Government contract DE-AC52-06NA25396 for Los Alamos National
# Laboratory (LANL), which is operated by Los Alamos National Security, LLC for
# the U.S. Department of Energy. The U.S. Government has rights to use,
# reproduce, and distribute this software.  NEITHER THE GOVERNMENT NOR LOS
# ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR
# ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.  If software is
# modified to produce derivative works, such modified software should be
# clearly marked, so as not to confuse it with the version available from
# LANL.
#
# THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.



GUFI_PWD=""

CONFIG="/etc/GUFI/config"
if [[ "$1" != "" ]]
then
    CONFIG="$1"
fi

__gufi() {
    # make sure the config file exists
    if [[ ! -f "${CONFIG}" ]]
    then
        >&2 echo "Could not find config file \"${CONFIG}\""
        exit 1
    fi

    root=$(readlink -m $(grep "IndexRoot=" "${CONFIG}"  | sed "s/^.*=//"))
    bfq=$(readlink -m $(grep "Executable=" ${CONFIG} | sed "s/^.*=//"))
    curr=$(printf "%s" "${COMP_WORDS[@]:${COMP_CWORD}}")
    path="${root}/${curr}"
    name=${path##*/} # basename without expanding

    COMPREPLY=()

    if [ "${name}" != "." ] && [ -d "${path}" ]
    then
        GUFI_PWD="${path}"

        # return all entries in the directory and directory names in subdirectories
        matches=$(${bfq} \
            -a \
            -e 0 \
            -z 1 \
            -d $' ' \
            -I "CREATE TABLE out(name TEXT, type TEXT)" \
            -S "INSERT INTO out SELECT name || '/', type FROM summary WHERE (level() == 1)" \
            -E "INSERT INTO out SELECT name || ' ', type FROM entries WHERE (level() == 0)" \
            -J "INSERT INTO aggregate.out SELECT * FROM out" \
            -G "SELECT name FROM out ORDER BY name ASC" \
            ${GUFI_PWD})

        # return all matches
        for match in ${matches}
        do
            COMPREPLY+=("${match}")
        done
    else
        # break up path into directory and name
        GUFI_PWD=$(dirname ${path})

        if [[ "${name}" =~ ^\. ]]
        then
            name="\\${name}"
        fi

        # search the index for matches on the name
        matches=$(${bfq} \
            -a \
            -e 0 \
            -z 1 \
            -d " " \
            -I "CREATE TABLE out(name TEXT, type TEXT)" \
            -S "INSERT INTO out SELECT name || '/', type FROM summary WHERE (name REGEXP \"^${name}\") AND (level() == 1)" \
            -E "INSERT INTO out SELECT name || ' ', type FROM entries WHERE (name REGEXP \"^${name}\") AND (level() == 0)" \
            -J "INSERT INTO aggregate.out SELECT * FROM out" \
            -G "SELECT name FROM out ORDER BY name ASC" \
            "${GUFI_PWD}")

        if [[ $(echo "${matches}" | wc -l) -eq "1" ]]
        then
            fullpath="${GUFI_PWD}/${matches}"
            COMPREPLY=("${fullpath#${root}/}")
        else
            # return all matches
            for match in ${matches}
            do
                COMPREPLY+=("${match}")
            done
        fi
    fi

    return 0
}

# register gufi_find, gufi_ls, and gufi_stats to be able to expand paths
complete -F __gufi gufi_find
complete -F __gufi gufi_ls
complete -F __gufi gufi_stats

# don't append spaces after tab completion
compopt -o nospace gufi_find
compopt -o nospace gufi_ls
compopt -o nospace gufi_stats
