#!/usr/bin/env bash

ACTUAL="/etc/GUFI/config"
EXAMPLE="${ACTUAL}.example"

if [[ ! -f "${ACTUAL}" ]]
then
    mkdir -p "$(dirname ${ACTUAL})"
    if [[ ! -f "${EXAMPLE}" ]]
    then
        mkdir -p "$(dirname ${EXAMPLE})"
        (
            echo "# Client Config";
            echo "# The actual file should be ${ACTUAL}"
            echo ""
            echo "# Hostname";
            echo "Server=lanl.gov";
            echo "";
            echo "# Positive Integer";
            echo "Port=22";
            echo "";
            echo "# location of paramiko directory";
            echo "# single string";
            echo "Paramiko=/path/to/paramiko"
        ) > "${EXAMPLE}"
        echo "Wrote example client configuration into ${EXAMPLE}"
    fi
    echo "Please make sure an actual client configuration file exists at ${ACTUAL}"
else
    echo "Nothing Done. ${ACTUAL} and ${EXAMPLE} both already exist."
fi
