#!/usr/bin/env python2.7
# This file is part of GUFI, which is part of MarFS, which is released
# under the BSD license.


# Copyright (c) 2017, Los Alamos National Security (LANS), LLC
# All rights reserved.

# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.

# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.

# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# -----
# NOTE:
# -----

# GUFI uses the C-Thread-Pool library.  The original version, written by
# Johan Hanssen Seferidis, is found at
# https://github.com/Pithikos/C-Thread-Pool/blob/master/LICENSE, and is
# released under the MIT License.  LANS, LLC added functionality to the
# original work.  The original work, plus LANS, LLC added functionality is
# found at https://github.com/jti-lanl/C-Thread-Pool, also under the MIT
# License.  The MIT License can be found at
# https://opensource.org/licenses/MIT.


# From Los Alamos National Security, LLC:
# LA-CC-15-039

# Copyright (c) 2017, Los Alamos National Security, LLC All rights reserved.
# Copyright 2017. Los Alamos National Security, LLC. This software was produced
# under U.S. Government contract DE-AC52-06NA25396 for Los Alamos National
# Laboratory (LANL), which is operated by Los Alamos National Security, LLC for
# the U.S. Department of Energy. The U.S. Government has rights to use,
# reproduce, and distribute this software.  NEITHER THE GOVERNMENT NOR LOS
# ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR
# ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.  If software is
# modified to produce derivative works, such modified software should be
# clearly marked, so as not to confuse it with the version available from
# LANL.

# THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.



import argparse
import os
import subprocess
import sys
import time

import query_builder as qb

BFQ_EXEC = os.path.join(os.path.dirname(os.path.dirname(os.path.realpath(__file__))), "bin", 'bfq')

SECONDS_PER_DAY = str(24 * 60 * 60)

'''file size units specified in GNU find.'''
filesize = {'b' : 512,
            'c' : 1,
            'w' : 2,
            'k' : 1024,
            'M' : 1048576,
            'G' : 1073741824}

def build_select(args):
    '''Build the SELECT portion of the queries for the treesummary, summary, and entries tables.'''
    tsummary = []
    summary  = ['name']
    entries  = []

    if args.select:
        entries += [args.select]

    return tsummary, summary, entries

def build_where(args, root_uid = 0, root_gid = 0):
    '''Build the WHERE portion of the queries for the treesummary, summary, and entries tables.'''
    tsummary = []
    summary  = []
    entries  = []

    # if not ((os.geteuid() == root_uid) or (os.getegid() == root_gid)):
    #     entries  += ['(uid == {})'.format(os.getuid())]
    #     # entries  += ['(uid == {}) OR (gid in {})'.format(os.getuid(), '(' + str(os.getgroups())[1:-1] + ')')]

    if args.amin is not None:
        entries += ['({} - atime) / 60 == {}'.format(time.time(), args.amin)]

    # if args.anewer is not None:

    if args.atime is not None:
        entries += ['({} - atime) / {} == {} '.format(time.time(), SECONDS_PER_DAY, args.atime)]

    if args.cmin is not None:
        entries += ['({} - ctime) / 60 == {}'.format(time.time(), args.cmin)]

    # if args.cnewer is not None:

    if args.ctime is not None:
        entries += ['({} - ctime) / {} == {} '.format(time.time(), SECONDS_PER_DAY, args.ctime)]

    if args.empty == True:
        summary += ['minsize == 0']
        entries += ['size == 0', '(type == \'f\') OR (type == \'d\')']

    if args.executable == True:
        entries += ['(mode & 64) == 64'] # 0100 have to use decimal or hexadecimal value because sqlite3 doesn't support octal

    if args.false == True:
        summary += ['0']
        entries += ['0']

    if args.gid is not None:
        summary += ['mingid <= {}'.format(args.gid), '{} <= maxgid'.format(args.gid)]
        entries += ['gid == {}'.format(args.gid)]

    if args.group is not None:
        entries += ['gid == {}'.format(args.group)]

    # if args.ilname is not None:

    if args.iname is not None:
        entries += ['name REGEXP \'(?i){}\'"'.format(args.name)]

    if args.inum is not None:
        entries += ['inode == {}'.format(args.inum)]

    # Behaves in the same way as -iwholename. This option is deprecated, so please do not use it.
    # if args.ipath is not None:

    # if args.iregex is not None:

    # if args.iwholename is not None:

    if args.links is not None:
        entries += ['nlink == {}'.format(args.links)]

    if args.lname is not None:
        entries += ['type == \'f\'', 'linkname REGEXP \'(?i){}\'"'.format(args.name)]

    if args.mmin is not None:
        entries += ['({} - mtime) / 60 == {}'.format(time.time(), args.mmin)]

    if args.mtime is not None:
        entries += ['({} - mtime) / {} == {} '.format(time.time(), SECONDS_PER_DAY, args.mtime)]

    if args.name is not None:
        entries += ['name REGEXP \'{}\''.format(args.name)]

    if args.newer is not None:
        entries += ['mtime > {}'.format(args.newer.st_mtime)]

    # if args.newerXY is not None:

    # if args.nouser == True:

    # # not handled here
    # if args.path is not None:

    # if args.perm is not None:

    if args.readable == True:
        entries += ['(mode & 256) == 256'] # 0400 have to use decimal or hexadecimal value because sqlite3 doesn't support octal

    # # not handled here
    # if args.regex is not None:

    if args.samefile is not None:
        entries += ['inode == {}'.format(args.samefile.st_ino)]

    if args.size is not None:
        size = args.size

        prefix = None
        if size[0] == '+' or size[0] == '-':
            prefix = size[0]
            size = size[1:]

        unit = 'b'
        if size[-1] in 'bcwkMG':
            unit = size[-1]
            size = size[:-1]

        # compute the actual size
        size = int(size) * filesize[unit]

        comp = '=='
        if prefix == '+':
            summary += ['minsize => {}'.format(size)]
            comp = '>'
        elif prefix == '-':
            summary += ['maxsize <= {}'.format(size)]
            comp = '<'

        entries += ['size {} {}'.format(comp, size)]

    if args.true == True:
        summary += ['1']
        entries += ['1']

    if args.type is not None:
        entries += ['type == "{}"'.format(args.type)]

    if args.uid is not None:
        summary += ['minuid <= {}'.format(args.uid), '{} <= maxuid'.format(args.uid)]
        entries += ['uid == {}'.format(args.uid)]

    # if args.used is not None:

    if args.user is not None:
        entries += ['uid == {}'.format(args.user)]

    # if args.wholename is not None:

    if args.writable == True:
        entries += ['(mode & 128) == 128'] # 0200 have to use decimal or hexadecimal value because sqlite3 doesn't support octal

    # if args.xtype is not None:

    # if args.context is not None:

    return tsummary, summary, entries

def build_group_by(args):
    '''Build the GROUP BY portion of the queries for the treesummary, summary, and entries tables.'''
    tsummary = []
    summary  = []
    entries  = []

    if args.group_by:
        entries += [args.group_by]
    return tsummary, summary, entries

def build_order_by(args):
    '''Build the ORDER BY portion of the queries for the treesummary, summary, and entries tables.'''
    tsummary = []
    summary  = []
    entries  = []

    if args.smallest:
        entries += ['size ASC']

    if args.largest:
        entries += ['size DESC']

    return tsummary, summary, entries

if __name__=='__main__':
    cwd = os.getcwd()

    parser = argparse.ArgumentParser(prog='GUFI', description='GUFI version of find')
    parser.add_argument('--version', '-v',                                                 action='version',                             version=os.path.basename(os.path.realpath(__file__)) + ' @GUFI_VERSION@')

    # GNU find options
    parser.add_argument('-amin',               metavar='n',          dest='amin',          type=qb.get_non_negative,                     help='File was last accessed n minutes ago.')
    # parser.add_argument('-anewer',             metavar='file',       dest='anewer',        type=qb.get_non_negative,                     help='File was last accessed more recently than file was modified.')
    parser.add_argument('-atime',              metavar='n',          dest='atime',         type=qb.get_non_negative,                     help='File was last accessed n*24 hours ago.')
    parser.add_argument('-cmin',               metavar='n',          dest='cmin',          type=qb.get_non_negative,                     help='File\'s status was last changed n minutes ago.')
    # parser.add_argument('-cnewer',             metavar='file',       dest='cnewer',        type=qb.get_non_negative,                     help='File\'s status was last changed more recently than file was modified.')
    parser.add_argument('-ctime',              metavar='n',          dest='ctime',         type=qb.get_non_negative,                     help='File\'s status was last changed n*24 hours ago.')
    parser.add_argument('-empty',                                    dest='empty',         action='store_true',                          help='File is empty and is either a regular file or a directory.')
    parser.add_argument('-executable',                               dest='executable',    action='store_true',                          help='Matches files which are executable and directories which are searchable (in a file name resolution sense).')
    parser.add_argument('-false',                                    dest='false',         action='store_true',                          help='File is false and is either a regular file or a directory.')
    # parser.add_argument('-fstype',             metavar='n',          dest='fstype',        type=str,                                     help='File is on a filesystem of type type.')
    parser.add_argument('-gid',                metavar='n',          dest='gid',           type=qb.get_gid,                              help='File\'s numeric group ID is n.')
    parser.add_argument('-group',              metavar='gname',      dest='group',         type=qb.get_group,                            help='File belongs to group gname (numeric group ID allowed).')
    # parser.add_argument('-ilname',             metavar='pattern',    dest='ilname',        type=str,                                     help='Like -lname, but the match is case insensitive.')
    parser.add_argument('-iname',              metavar='pattern',    dest='iname',         type=str,                                     help='Like -name, but the match is case insensitive.')
    parser.add_argument('-inum',               metavar='n',          dest='inum',          type=qb.get_non_negative,                     help='File has inode number n. It is normally easier to use the -samefile test instead.')
    # parser.add_argument('-ipath',              metavar='pattern',    dest='ipath',         type=str,                                     help='Behaves in the same way as -iwholename. This option is deprecated, so please do not use it.')
    # parser.add_argument('-iregex',             metavar='pattern',    dest='iregex',        type=str,                                     help='Like -regex, but the match is case insensitive.')
    # parser.add_argument('-iwholename',         metavar='pattern',    dest='iwholename',    type=str,                                     help='Like -wholename, but the match is case insensitive.')
    parser.add_argument('-links',              metavar='n',          dest='links',         type=qb.get_non_negative,                     help='File has n links.')
    parser.add_argument('-lname',              metavar='pattern',    dest='lname' ,        type=str,                                     help='File is a symbolic link whose contents match shell pattern pattern.')
    parser.add_argument('-mmin',               metavar='n',          dest='mmin',          type=qb.get_non_negative,                     help='File\'s data was last modified n minutes ago.')
    parser.add_argument('-mtime',              metavar='n',          dest='mtime',         type=qb.get_non_negative,                     help='File\'s data was last modified n*24 hours ago.')
    parser.add_argument('-name',               metavar='pattern',    dest='name',          type=str,                                     help='Base of file name (the path with the leading directories removed) matches shell pattern pattern.')
    parser.add_argument('-newer',              metavar='file',       dest='newer',         type=os.stat,                                 help='File was modified more recently than file.')
    # parser.add_argument('-newerXY',            metavar='reference',  dest='newerXY',       type=str,                                     help='Compares the timestamp of the current file with reference.')
    # parser.add_argument('-nouser',                                   dest='nouser',        type='store_true',                            help='No user corresponds to file\'s numeric user ID.')
    parser.add_argument('-path',               metavar='pattern',    dest='path',          type=str, action='append', default=[],        help='File name matches shell pattern pattern.')
    # parser.add_argument('-perm',               metavar='mode',       dest='perm',          type=str,                                     help='File\'s  permission bits')
    parser.add_argument('-readable',                                 dest='readable',      action='store_true',                          help='Matches files which are readable.')
    # parser.add_argument('-regex',              metavar='pattern',    dest='regex',         type=str,                                     help='File name matches regular expression pattern.')
    parser.add_argument('-samefile',           metavar='name',       dest='samefile',      type=os.stat,                                 help='File refers to the same inode as name.')
    parser.add_argument('-size',               metavar='n',          dest='size',          type=qb.get_size,                             help='')
    parser.add_argument('-true',                                     dest='true',          action='store_true',                          help='Always true')
    parser.add_argument('-type',               metavar='c',          dest='type',          type=qb.get_char,                             help='File is of type c')
    parser.add_argument('-uid',                metavar='n',          dest='uid',           type=qb.get_uid,                              help='File\'s numeric user ID is n.')
    # parser.add_argument('-used',               metavar='n',          dest='used',          type=qb.get_non_negative,                     help='File was last accessed n days after its status was last changed.')
    parser.add_argument('-user',               metavar='uname',      dest='user',          type=qb.get_user,                             help='File is owned by user uname (numeric user ID allowed).')
    parser.add_argument('-wholename',          metavar='pattern',    dest='wholename',     type=str, action='append', default=[],        help='See -path. This alternative is less portable than -path.')
    parser.add_argument('-writable',                                 dest='writable',      action='store_true',                          help='Matches files which are writable.')
    # parser.add_argument('-xtype',              metavar='c',          dest='xtype',         type=qb.get_char,                             help='The same as -type unless the file is a symbolic link.')
    # parser.add_argument('-context',            metavar='pattern',    dest='context',       type=str,                                     help='(SELinux only) Security context of the file matches glob pattern.')

    parser.add_argument('-maxdepth',           metavar='levels',     dest='maxdepth',      type=qb.get_non_negative,                     help='Descend at most levels (a non-negative integer) levels of directories below the command line arguments. -maxdepth 0 means only apply the tests and actions to the command line arguments.')
    parser.add_argument('-mindepth',           metavar='levels',     dest='mindepth',      type=qb.get_non_negative,                     help='Do not apply any tests or actions at levels less than levels (a non-negative integer). -mindepth 1 means process all files except the command line arguments.')

    # # GNU find optional arguments
    parser.add_argument('starting-point',      metavar='root',                            type=str,  nargs='+',      default=cwd,       help='top-most directory to search from')

    # GUFI specific arguments
    parser.add_argument('--select',            metavar='cols',       dest='select',        type=str,                  default='*',       help='comma separated columns (default: *)')
    parser.add_argument('--group_by',          metavar='cols',       dest='group_by',      type=str,                                     help='comma separated columns (default: None)')
    parser.add_argument('--delim',             metavar='c',          dest='delim',         type=qb.get_char,                             help='delimiter separating output columns')
    parser.add_argument('--num_results',       metavar='n',          dest='num_results',   type=qb.get_non_negative,                     help='first n results')
    parser.add_argument('--smallest',                                dest='smallest',      action='store_true',                          help='top n smallest files')
    parser.add_argument('--largest',                                 dest='largest',       action='store_true',                          help='top n largest files')
    parser.add_argument('--threads', '-t',     metavar='n',          dest='threads',       type=qb.get_positive,      default=qb.cpus(), help='number of threads')
    parser.add_argument('--intermediate_dbs',  metavar='n',          dest='intermediates', type=qb.get_non_negative,                     help='number of intermediate databases')
    parser.add_argument('--intermediate_skip', metavar='n',          dest='skip',          type=qb.get_non_negative,                     help='number of intermediate databases to skip when selecting the next database')
    parser.add_argument('--aggregate',         metavar='True/False', dest='aggregate',     type=qb.get_bool,          default=False,     help='do not aggregate results before printing')
    parser.add_argument('--bfq',                                     dest='bfq',                                      default=BFQ_EXEC,  help='Location of bfq executable')

    args = parser.parse_args();

    # create the find command
    find = qb.find_dir(getattr(args, 'starting-point'), [os.path.normpath(path) for path in args.path], [os.path.normpath(path) for path in args.wholename])
    find_out, find_err = find.communicate()

    # check for data in stdout, not the return code of find
    if len(find_out) == 0:
        # if there are errors, print them
        if len(find_err):
            sys.stderr.write('Error: find returned: {}\n{}\n'.format(os.strerror(find.returncode), find_err))
        # otherwise, nothing was found
        else:
            sys.stderr.write('Error: No directories found while searching in "{}" for "{}"\n'.format(getattr(args, 'starting-point'), ' '.join([os.path.normpath(path) for path in args.path] + [os.path.normpath(path) for path in args.wholename])))
        sys.exit(find.returncode)
    # if there is data and errors, ignore the errors

    # generate the queries
    tsummary_select,   summary_select,   entries_select   = build_select(args)
    tsummary_where,    summary_where,    entries_where    = build_where(args)
    tsummary_group_by, summary_group_by, entries_group_by = build_group_by(args)
    tsummary_order_by, summary_order_by, entries_order_by = build_order_by(args)

    tsummary = qb.build_query(tsummary_select,
                             ['treesummary'],
                             tsummary_where,
                             tsummary_group_by,
                             tsummary_order_by,
                             args.num_results)

    summary = qb.build_query(summary_select,
                             ['summary'],
                             summary_where,
                             summary_group_by,
                             summary_order_by,
                             args.num_results)

    initial = qb.build_query(entries_select,
                             ['entries'],
                             entries_where,
                             entries_group_by,
                             entries_order_by,
                             args.num_results)

    intermediate = final = qb.build_query(['*'],
                                          ['entries'],
                                          entries_where,
                                          entries_group_by,
                                          entries_order_by,
                                          args.num_results)

    # create the bfq command
    bfq_cmd = [args.bfq,
               '-p', '-P',
               '-e', str(int(not args.aggregate)),
               '-n', str(args.threads)]

    # if len(tsummary):
    #     bfq_cmd += ['-T', tsummary]

    # if len(summary):
    #     bfq_cmd += ['-S', summary]

    if len(initial):
        bfq_cmd += ['-E', initial]

    if len(intermediate):
        bfq_cmd += ['-J', intermediate]

    if len(final):
        bfq_cmd += ['-G', final]

    if args.delim:
        bfq_cmd += ['-d', args.delim]

    if args.intermediates:
        bfq_cmd += ['-v', str(args.intermediates)]

    if args.skip:
        bfq_cmd += ['-w', str(args.skip)]

    if args.maxdepth:
        bfq_cmd += ['-z', str(args.maxdepth)]

    if args.mindepth:
        bfq_cmd += ['-y', str(args.mindepth)]

    bfq = subprocess.Popen(bfq_cmd + find_out.split()) # positional arguments must appear after flags
    bfq.communicate()                                  # block until bfq finishes

    sys.exit(bfq.returncode)
